# Generated by Django 5.2 on 2025-06-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del servicio')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('duracion', models.IntegerField(help_text='Duración en minutos', verbose_name='Duración en minutos')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios/', verbose_name='Imagen del servicio')),
                ('icono', models.CharField(choices=[('fa-solid fa-hands', 'Masaje General'), ('fa-solid fa-hot-tub-person', 'Sauna'), ('fa-solid fa-face-smile', 'Facial'), ('fa-solid fa-spray-can-sparkles', 'Aromaterapia'), ('fa-solid fa-droplet', 'Hidroterapia'), ('fa-solid fa-spa', 'Spa'), ('fa-solid fa-heart', 'Bienestar'), ('fa-solid fa-wind', 'Relajación'), ('fa-solid fa-massage', 'Masaje Específico'), ('fa-solid fa-bottle-droplet', 'Aceites Esenciales'), ('fa-solid fa-hand-holding-heart', 'Cuidado Personal'), ('fa-solid fa-cloud', 'Vapor')], default='fa-solid fa-spa', max_length=50, verbose_name='Ícono')),
                ('hora_inicio', models.TimeField(default='09:00', help_text='Hora de inicio de atención')),
                ('hora_fin', models.TimeField(default='20:00', help_text='Hora de fin de atención')),
                ('intervalo', models.IntegerField(default=60, help_text='Intervalo entre turnos en minutos')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
    ]
