# Generated by Django 5.2 on 2025-04-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del servicio')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('duracion', models.IntegerField(verbose_name='Duración en minutos')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('imagen', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL de la imagen')),
                ('icono', models.CharField(choices=[('fa-spa', 'Spa'), ('fa-massage', 'Masaje'), ('fa-heart', 'Bienestar'), ('fa-leaf', 'Natural'), ('fa-gem', 'Premium'), ('fa-star', 'Estrella'), ('fa-crown', 'VIP'), ('fa-heartbeat', 'Salud'), ('fa-paw', 'Mascotas'), ('fa-sun', 'Relax')], default='fa-spa', max_length=50, verbose_name='Ícono')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
    ]
