# Generated by Django 5.2 on 2025-04-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_servicio_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='icono',
            field=models.CharField(choices=[('fa-solid fa-hands', 'Masaje General'), ('fa-solid fa-hot-tub-person', 'Sauna'), ('fa-solid fa-face-smile', 'Facial'), ('fa-solid fa-spray-can-sparkles', 'Aromaterapia'), ('fa-solid fa-droplet', 'Hidroterapia'), ('fa-solid fa-spa', 'Spa'), ('fa-solid fa-heart', 'Bienestar'), ('fa-solid fa-wind', 'Relajación'), ('fa-solid fa-massage', 'Masaje Específico'), ('fa-solid fa-bottle-droplet', 'Aceites Esenciales'), ('fa-solid fa-hand-holding-heart', 'Cuidado Personal'), ('fa-solid fa-cloud', 'Vapor')], default='fa-solid fa-spa', max_length=50, verbose_name='Ícono'),
        ),
    ]
