# Generated by Django 5.2 on 2025-04-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_servicio_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='hora_fin',
            field=models.TimeField(default='20:00', help_text='Hora de fin de atención'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='hora_inicio',
            field=models.TimeField(default='09:00', help_text='Hora de inicio de atención'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='intervalo',
            field=models.IntegerField(default=60, help_text='Intervalo entre turnos en minutos'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='duracion',
            field=models.IntegerField(help_text='Duración en minutos', verbose_name='Duración en minutos'),
        ),
    ]
