# Generated by Django 5.2 on 2025-06-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_servicio_hora_fin_servicio_hora_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/', verbose_name='Imagen del servicio'),
        ),
    ]
