# Generated by Django 5.2 on 2025-06-12 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0005_alter_servicio_imagen'),
        ('usuarios', '0003_profesional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='Hora de fin')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('completado', 'Completado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='usuarios.profesional', verbose_name='Profesional')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['-fecha', '-hora_inicio'],
                'unique_together': {('fecha', 'hora_inicio', 'servicio')},
            },
        ),
    ]
