# Generated by Django 5.2 on 2025-06-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='descuento_aplicado',
            field=models.BooleanField(default=False, verbose_name='Descuento aplicado'),
        ),
        migrations.AddField(
            model_name='turno',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('debito', 'Tarjeta de Débito'), ('credito', 'Tarjeta de Crédito')], default='efectivo', max_length=20, verbose_name='Método de pago'),
        ),
        migrations.AddField(
            model_name='turno',
            name='pagado',
            field=models.BooleanField(default=False, verbose_name='Pagado'),
        ),
        migrations.AddField(
            model_name='turno',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total a pagar'),
        ),
    ]
