# Generated by Django 5.2 on 2025-06-12 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Foto de perfil')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('tipo_usuario', models.CharField(choices=[('cliente', 'Cliente'), ('profesional', 'Profesional'), ('administrador', 'Administrador')], default='cliente', help_text='Determina los permisos y accesos del usuario', max_length=20, verbose_name='Tipo de usuario')),
                ('numero_licencia', models.CharField(blank=True, help_text='Solo para profesionales', max_length=50, verbose_name='Número de licencia profesional')),
                ('especialidad', models.CharField(blank=True, help_text='Especialidad del profesional', max_length=100, verbose_name='Especialidad')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'permissions': [('can_manage_all_appointments', 'Puede gestionar todos los turnos'), ('can_view_reports', 'Puede ver reportes'), ('can_manage_professionals', 'Puede gestionar profesionales')],
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(help_text='Nombre completo del profesional', max_length=150, verbose_name='Nombre completo')),
                ('especialidad', models.CharField(help_text='Especialidad principal del profesional', max_length=100, verbose_name='Especialidad principal')),
                ('especialidades_secundarias', models.TextField(blank=True, help_text='Otras especialidades separadas por comas', verbose_name='Especialidades secundarias')),
                ('contacto', models.EmailField(help_text='Email profesional de contacto', max_length=254, verbose_name='Email de contacto')),
                ('telefono_profesional', models.CharField(blank=True, max_length=20, verbose_name='Teléfono profesional')),
                ('numero_matricula', models.CharField(help_text='Número de matrícula profesional', max_length=50, unique=True, verbose_name='Número de matrícula')),
                ('colegio_profesional', models.CharField(blank=True, help_text='Colegio o asociación profesional', max_length=100, verbose_name='Colegio profesional')),
                ('hora_inicio_lunes', models.TimeField(blank=True, null=True, verbose_name='Lunes - Inicio')),
                ('hora_fin_lunes', models.TimeField(blank=True, null=True, verbose_name='Lunes - Fin')),
                ('hora_inicio_martes', models.TimeField(blank=True, null=True, verbose_name='Martes - Inicio')),
                ('hora_fin_martes', models.TimeField(blank=True, null=True, verbose_name='Martes - Fin')),
                ('hora_inicio_miercoles', models.TimeField(blank=True, null=True, verbose_name='Miércoles - Inicio')),
                ('hora_fin_miercoles', models.TimeField(blank=True, null=True, verbose_name='Miércoles - Fin')),
                ('hora_inicio_jueves', models.TimeField(blank=True, null=True, verbose_name='Jueves - Inicio')),
                ('hora_fin_jueves', models.TimeField(blank=True, null=True, verbose_name='Jueves - Fin')),
                ('hora_inicio_viernes', models.TimeField(blank=True, null=True, verbose_name='Viernes - Inicio')),
                ('hora_fin_viernes', models.TimeField(blank=True, null=True, verbose_name='Viernes - Fin')),
                ('hora_inicio_sabado', models.TimeField(blank=True, null=True, verbose_name='Sábado - Inicio')),
                ('hora_fin_sabado', models.TimeField(blank=True, null=True, verbose_name='Sábado - Fin')),
                ('hora_inicio_domingo', models.TimeField(blank=True, null=True, verbose_name='Domingo - Inicio')),
                ('hora_fin_domingo', models.TimeField(blank=True, null=True, verbose_name='Domingo - Fin')),
                ('disponibilidad_notas', models.TextField(blank=True, help_text='Información adicional sobre horarios y disponibilidad', verbose_name='Notas sobre disponibilidad')),
                ('biografia', models.TextField(blank=True, help_text='Información sobre experiencia y formación', verbose_name='Biografía profesional')),
                ('experiencia_anos', models.PositiveIntegerField(default=0, help_text='Años de experiencia profesional', verbose_name='Años de experiencia')),
                ('foto_profesional', models.ImageField(blank=True, help_text='Foto para mostrar en el perfil profesional', null=True, upload_to='profesionales/', verbose_name='Foto profesional')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('vacaciones', 'En Vacaciones'), ('licencia', 'En Licencia')], default='activo', max_length=20, verbose_name='Estado')),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio en el spa', verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha de finalización (si aplica)', null=True, verbose_name='Fecha de fin')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones internas sobre el profesional', verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('servicios_especialidad', models.ManyToManyField(blank=True, help_text='Servicios en los que se especializa este profesional', to='servicios.servicio', verbose_name='Servicios de especialidad')),
                ('usuario', models.OneToOneField(help_text='Usuario asociado al profesional', on_delete=django.db.models.deletion.CASCADE, related_name='profesional', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
                'ordering': ['nombre_completo'],
                'permissions': [('can_view_professional_schedule', 'Puede ver horarios de profesionales'), ('can_manage_professional_data', 'Puede gestionar datos de profesionales')],
            },
        ),
    ]
