# Generated by Django 5.2 on 2025-06-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'permissions': [('can_manage_all_appointments', 'Puede gestionar todos los turnos'), ('can_view_reports', 'Puede ver reportes'), ('can_manage_professionals', 'Puede gestionar profesionales')], 'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AddField(
            model_name='perfil',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='especialidad',
            field=models.CharField(blank=True, help_text='Especialidad del profesional', max_length=100, verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='numero_licencia',
            field=models.CharField(blank=True, help_text='Solo para profesionales', max_length=50, verbose_name='Número de licencia profesional'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tipo_usuario',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('profesional', 'Profesional'), ('administrador', 'Administrador')], default='cliente', help_text='Determina los permisos y accesos del usuario', max_length=20, verbose_name='Tipo de usuario'),
        ),
    ]
