# Generated by Django 5.2 on 2025-05-29 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('profesional', 'Profesional'), ('administrador', 'Administrador')], default='cliente', max_length=20, verbose_name='Rol'),
        ),
    ]
