# Generated by Django 5.2 on 2025-05-30 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0005_alter_servicio_imagen'),
        ('usuarios', '0002_perfil_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecialidadSecundaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_competencia', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado'), ('experto', 'Experto')], default='intermedio', max_length=20, verbose_name='Nivel de Competencia')),
            ],
            options={
                'verbose_name': 'Especialidad Secundaria',
                'verbose_name_plural': 'Especialidades Secundarias',
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('especialidad', models.CharField(choices=[('masajes', 'Masajes Terapéuticos'), ('faciales', 'Tratamientos Faciales'), ('corporales', 'Tratamientos Corporales'), ('aromaterapia', 'Aromaterapia'), ('reflexologia', 'Reflexología'), ('hidroterapia', 'Hidroterapia'), ('spa', 'Servicios de Spa General'), ('bienestar', 'Bienestar Integral'), ('estetica', 'Estética Avanzada'), ('relajacion', 'Técnicas de Relajación')], max_length=50, verbose_name='Especialidad Principal')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email_profesional', models.EmailField(blank=True, max_length=254, verbose_name='Email Profesional')),
                ('numero_licencia', models.CharField(blank=True, max_length=50, verbose_name='Número de Licencia')),
                ('años_experiencia', models.PositiveIntegerField(default=0, verbose_name='Años de Experiencia')),
                ('certificaciones', models.TextField(blank=True, help_text='Lista de certificaciones y cursos', verbose_name='Certificaciones')),
                ('hora_inicio_disponibilidad', models.TimeField(default='09:00', verbose_name='Hora de Inicio')),
                ('hora_fin_disponibilidad', models.TimeField(default='18:00', verbose_name='Hora de Fin')),
                ('dias_disponibles', models.CharField(default='lunes,martes,miercoles,jueves,viernes', help_text='Días de la semana separados por comas (lunes,martes,miercoles...)', max_length=100, verbose_name='Días Disponibles')),
                ('biografia', models.TextField(blank=True, verbose_name='Biografía Profesional')),
                ('foto_profesional', models.ImageField(blank=True, null=True, upload_to='profesionales/', verbose_name='Foto Profesional')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_contratacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Contratación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('especialidades_secundarias', models.ManyToManyField(blank=True, related_name='profesionales_secundarios', through='usuarios.EspecialidadSecundaria', to='usuarios.profesional', verbose_name='Especialidades Secundarias')),
                ('servicios_que_ofrece', models.ManyToManyField(blank=True, related_name='profesionales', to='servicios.servicio', verbose_name='Servicios que Ofrece')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesional', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.AddField(
            model_name='especialidadsecundaria',
            name='profesional_especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesionales_con_esta_especialidad', to='usuarios.profesional'),
        ),
        migrations.AddField(
            model_name='especialidadsecundaria',
            name='profesional_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialidades_extras', to='usuarios.profesional'),
        ),
        migrations.AlterUniqueTogether(
            name='especialidadsecundaria',
            unique_together={('profesional_principal', 'profesional_especialidad')},
        ),
    ]
