# -*- coding: utf-8 -*-
"""
Django settings for GestorSpa project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproje# Email settings
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'gestorspa.sistema@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'GestorSPA Sistema <gestorspa.sistema@gmail.com>')
SERVER_EMAIL = os.getenv('SERVER_EMAIL', 'gestorspa.sistema@gmail.com')

# Email backend para desarrollo y producción
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Para desarrollo, descomentar la siguiente línea para usar backend de consola
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Configuraciones adicionales para password reset y rate limiting
EMAIL_TIMEOUT = 60  # timeout en segundos
PASSWORD_RESET_TIMEOUT = 3600  # 1 hora en segundos

# Cache para rate limiting (usando memoria local por defecto)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 3600,  # 1 hora
    }
}cs/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# Configurar encoding UTF-8 antes que cualquier otra cosa
import sys
import os

# Configurar encoding del sistema
sys.dont_write_bytecode = True
os.environ['PYTHONIOENCODING'] = 'utf-8'

# Importar configuración de encoding
try:
    from GestorSpa.encoding_config import configurar_encoding
    configurar_encoding()
except ImportError:
    pass

from pathlib import Path
import os
import sys
from dotenv import load_dotenv

# Configurar encoding UTF-8 para el sistema
if sys.platform.startswith('win'):
    import locale
    try:
        locale.setlocale(locale.LC_ALL, 'es_ES.UTF-8')
    except locale.Error:
        try:
            locale.setlocale(locale.LC_ALL, 'Spanish_Spain.1252')
        except locale.Error:
            pass
    
# Forzar encoding UTF-8 en Python
import codecs
if hasattr(sys.stdout, 'detach'):
    try:
        sys.stdout = codecs.getwriter('utf-8')(sys.stdout.detach())
        sys.stderr = codecs.getwriter('utf-8')(sys.stderr.detach())
    except:
        pass

# Cargar variables de entorno
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG') == 'True'

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver']

# Configuración para password reset y emails
SITE_ID = 1

# Configuración del dominio para desarrollo
# Esto soluciona el problema de 'NoneType' object has no attribute 'get_host'
if DEBUG:
    EMAIL_HOST_DOMAIN = 'localhost:8000'
    EMAIL_USE_SSL = False
    EMAIL_USE_TLS = True
else:
    EMAIL_HOST_DOMAIN = 'tu-dominio.com'  # Cambiar en producción


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'GestorSpa.apps.usuarios',
    'GestorSpa.apps.turnos',
    'GestorSpa.apps.servicios',
]

MIDDLEWARE = [
    'GestorSpa.middleware.UTF8EncodingMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'GestorSpa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GestorSpa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': BASE_DIR / os.getenv('DB_NAME', 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = os.getenv('LANGUAGE_CODE', 'es-ar')

TIME_ZONE = os.getenv('TIME_ZONE', 'America/Argentina/Buenos_Aires')

USE_I18N = os.getenv('USE_I18N', 'True') == 'True'

USE_TZ = os.getenv('USE_TZ', 'True') == 'True'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = os.getenv('STATIC_URL', 'static/')
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = os.getenv('MEDIA_URL', '/media/')
MEDIA_ROOT = BASE_DIR / 'media'

# Configuraciones de encoding y archivos
FILE_CHARSET = 'utf-8'
DEFAULT_CHARSET = 'utf-8'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Auth settings
LOGIN_REDIRECT_URL = os.getenv('LOGIN_REDIRECT_URL', 'home')
LOGIN_URL = os.getenv('LOGIN_URL', 'login')
LOGOUT_REDIRECT_URL = os.getenv('LOGOUT_REDIRECT_URL', 'home')

# Email settings
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', 'gestorspa.sistema@gmail.com')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'GestorSPA Sistema <gestorspa.sistema@gmail.com>')
SERVER_EMAIL = os.getenv('SERVER_EMAIL', 'gestorspa.sistema@gmail.com')

# Email backend para desarrollo y producción
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Para desarrollo, descomentar la siguiente línea para usar backend de consola
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Configuraciones adicionales para password reset y rate limiting
EMAIL_TIMEOUT = 60  # timeout aumentado a 60 segundos
PASSWORD_RESET_TIMEOUT = 3600  # 1 hora en segundos

# Configuraciones para manejar rate limiting de Gmail
EMAIL_MAX_RECIPIENTS = 1  # Un destinatario por email
EMAIL_THROTTLE_FACTOR = 1.0  # Factor de throttling

# Headers adicionales para evitar spam
EMAIL_SUBJECT_PREFIX = '[GestorSPA] '
EMAIL_USE_LOCALTIME = True

# Configuración mejorada de logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'django.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'django.core.mail': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'GestorSpa.custom_auth_views': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}
